-- Course
-- Assignements

CREATE TABLE JM3190810_ONE_TO_MANY_UNI_COURSE(
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(256) NOT NULL
)

CREATE TABLE JM3190810_ONE_TO_MANY_UNI_ASSIGNMENT(
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(256) NOT NULL,
COURSE_ID BIGINT,
FOREIGN KEY(COURSE_ID) REFERENCES JM3190810_ONE_TO_MANY_UNI_COURSE(ID)
)