CREATE TABLE JM3190810_OTO_BI_ENGINE(
ID BIGINT AUTO_INCREMENT,
NAME VARCHAR(50),
SPEED NUMBER,
PRIMARY KEY(ID)
)


CREATE TABLE JM3190810_OTO_BI_CAR(
ID BIGINT AUTO_INCREMENT,
NAME VARCHAR(50),
COLOR VARCHAR(20),
ENGINE_ID BIGINT,
PRIMARY KEY(ID),
FOREIGN KEY(ENGINE_ID) REFERENCES JM3190810_OTO_BI_ENGINE(ID)
)